In [7]:
import pandas as pd
import os
import re
import glob

In [8]:
folder_path = "/Users/edwin2/Desktop/DM projektas/nusikalstamumas"

# Surandame visus CSV failus
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

for file in csv_files:

    filename = os.path.basename(file)

    # Ištraukiame metus (4 skaitmenys)
    match = re.search(r"\d{4}", filename)

    if match:
        year = match.group()

        # Sukuriame DataFrame
        df = pd.read_csv(file, sep=';')

        # Sukuriame kintamojo pavadinimą
        variable_name = f"nusikalstamumas_{year}"

        # Išsaugome kaip atskirą DataFrame kintamąjį
        globals()[variable_name] = df


df_list = []

for var_name in list(globals().keys()):
    if re.match(r"nusikalstamumas_\d{4}", var_name):
        df = globals()[var_name].copy()
        year = int(var_name.split("_")[1])
        df["Metai"] = year
        df_list.append(df)

nusikalstamumas_all = pd.concat(df_list, ignore_index=True)

In [9]:
nusikalstamumas_metais_all = nusikalstamumas_all[nusikalstamumas_all['Mėnuo'] == 'Sausis - Gruodis']

nusikalstamumas_metais = nusikalstamumas_metais_all[['Metai', 'Savivaldybė', 'Nusikaltimai']]


nusikalstamumas_metais

       Metai          Savivaldybė  Nusikaltimai
8       2015           Respublika         68240
20      2015      Akmenės rajonas           570
32      2015     Joniškio rajonas           716
44      2015     Jurbarko rajonas           596
56      2015  Kaišiadorių rajonas           637
...      ...                  ...           ...
14069   2018         Druskininkai           238
14070   2018      Alytaus rajonas           404
14071   2018           Elektrėnai           349
14072   2018    Ignalinos rajonas           336
14073   2018      Jonavos rajonas           864

[1341 rows x 3 columns]

In [10]:
nusikalstamumas_metais['Nusikaltimai'] = (
    nusikalstamumas_metais['Nusikaltimai']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .str.strip()
)

nusikalstamumas_metais['Nusikaltimai'] = pd.to_numeric(
    nusikalstamumas_metais['Nusikaltimai'], errors='coerce'
)

# Patikrinam dtype
nusikalstamumas_metais['Nusikaltimai'].dtype

nusikalstamumas_metais

       Metai          Savivaldybė  Nusikaltimai
8       2015           Respublika         68240
20      2015      Akmenės rajonas           570
32      2015     Joniškio rajonas           716
44      2015     Jurbarko rajonas           596
56      2015  Kaišiadorių rajonas           637
...      ...                  ...           ...
14069   2018         Druskininkai           238
14070   2018      Alytaus rajonas           404
14071   2018           Elektrėnai           349
14072   2018    Ignalinos rajonas           336
14073   2018      Jonavos rajonas           864

[1341 rows x 3 columns]

In [11]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3,
                       ):
    print(nusikalstamumas_metais)

       Metai              Savivaldybė  Nusikaltimai
8       2015               Respublika         68240
20      2015          Akmenės rajonas           570
32      2015         Joniškio rajonas           716
44      2015         Jurbarko rajonas           596
56      2015      Kaišiadorių rajonas           637
68      2015   Kalvarijos savivaldybė           282
80      2015            Kauno miestas          9068
92      2015            Kauno rajonas          1688
104     2015  Kazlų Rūdos savivaldybė           190
116     2015           Kelmės rajonas           566
128     2015         Kėdainių rajonas          1066
140     2015        Klaipėdos miestas          4991
152     2015          Alytaus miestas          1206
164     2015        Klaipėdos rajonas           725
176     2015        Kretingos rajonas           368
188     2015         Kupiškio rajonas           437
200     2015          Lazdijų rajonas           430
212     2015          Marijampolės PK          1607
224     2015         Mažeikių rajonas          1004
236     2015           Molėtų rajonas           372
248     2015                  Neringa            34
260     2015      Pagėgių savivaldybė           196
272     2015         Pakruojo rajonas           615
284     2015         Anykščių rajonas           437
296     2015                  Palanga           372
308     2015        Panevėžio miestas          2152
320     2015        Panevėžio rajonas           590
332     2015         Pasvalio rajonas           628
344     2015          Plungės rajonas           630
356     2015           Prienų rajonas           477
368     2015      Radviliškio rajonas           870
380     2015         Raseinių rajonas           708
392     2015      Rietavo savivaldybė           111
404     2015         Rokiškio rajonas           653
416     2015                Birštonas            45
428     2015           Skuodo rajonas           172
440     2015            Šakių rajonas           568
452     2015       Šalčininkų rajonas           987
464     2015          Šiaulių miestas          2683
476     2015          Šiaulių rajonas           683
488     2015          Šilalės rajonas           569
500     2015          Šilutės rajonas           768
512     2015         Širvintų rajonas           319
524     2015       Švenčionių rajonas           411
536     2015         Tauragės rajonas           786
548     2015            Biržų rajonas           491
560     2015           Telšių rajonas          1099
572     2015            Trakų rajonas           701
584     2015         Ukmergės rajonas           534
596     2015           Utenos rajonas           852
608     2015          Varėnos rajonas           466
620     2015      Vilkaviškio rajonas           675
632     2015         Vilniaus miestas         15718
644     2015         Vilniaus rajonas          1874
656     2015                Visaginas           244
668     2015           Zarasų rajonas           277
680     2015             Druskininkai           341
692     2015          Alytaus rajonas           487
704     2015               Elektrėnai           384
716     2015        Ignalinos rajonas           236
728     2015          Jonavos rajonas           878
740     2014               Respublika         74581
752     2014          Akmenės rajonas           637
764     2014         Joniškio rajonas           789
776     2014         Jurbarko rajonas           717
788     2014      Kaišiadorių rajonas           635
800     2014   Kalvarijos savivaldybė           315
812     2014            Kauno miestas          8484
824     2014            Kauno rajonas          2023
836     2014  Kazlų Rūdos savivaldybė           245
848     2014           Kelmės rajonas           759
860     2014         Kėdainių rajonas          1527
872     2014        Klaipėdos miestas          4987
884     2014          Alytaus miestas          1438
896     2014        Klaipėdos rajonas           741
908     2014        Kretingos rajonas           401
920     2014         Kupiškio rajonas           553
932     2014          Lazdijų rajonas           476
944     2014          Marijampolės PK          1687
956     2014         Mažeikių rajonas          1352
968     2014           Molėtų rajonas           287
980     2014                  Neringa            26
992     2014      Pagėgių savivaldybė           234
1004    2014         Pakruojo rajonas           674
1016    2014         Anykščių rajonas           564
1028    2014                  Palanga           564
1040    2014        Panevėžio miestas          2075
1052    2014        Panevėžio rajonas           751
1064    2014         Pasvalio rajonas           860
1076    2014          Plungės rajonas           806
1088    2014           Prienų rajonas           544
1100    2014      Radviliškio rajonas           971
1112    2014         Raseinių rajonas           993
1124    2014      Rietavo savivaldybė           113
1136    2014         Rokiškio rajonas           817
1148    2014                Birštonas            69
1160    2014           Skuodo rajonas           186
1172    2014            Šakių rajonas           500
1184    2014       Šalčininkų rajonas          1098
1196    2014          Šiaulių miestas          2834
1208    2014          Šiaulių rajonas           751
1220    2014          Šilalės rajonas           395
1232    2014          Šilutės rajonas           979
1244    2014         Širvintų rajonas           388
1256    2014       Švenčionių rajonas           444
1268    2014         Tauragės rajonas           717
1280    2014            Biržų rajonas           764
1292    2014           Telšių rajonas          1149
1304    2014            Trakų rajonas           679
1316    2014         Ukmergės rajonas           786
1328    2014           Utenos rajonas           959
1340    2014          Varėnos rajonas           408
1352    2014      Vilkaviškio rajonas           779
1364    2014         Vilniaus miestas         16947
1376    2014         Vilniaus rajonas          2264
1388    2014                Visaginas           354
1400    2014           Zarasų rajonas           355
1412    2014             Druskininkai           406
1424    2014          Alytaus rajonas           513
1436    2014               Elektrėnai           377
1448    2014        Ignalinos rajonas           450
1460    2014          Jonavos rajonas           985
1464    2016               Respublika         55950
1465    2016          Akmenės rajonas           391
1466    2016         Joniškio rajonas           362
1467    2016         Jurbarko rajonas           524
1468    2016      Kaišiadorių rajonas           628
1469    2016   Kalvarijos savivaldybė           318
1470    2016            Kauno miestas          7426
1471    2016            Kauno rajonas          1267
1472    2016  Kazlų Rūdos savivaldybė           189
1473    2016           Kelmės rajonas           478
1474    2016         Kėdainių rajonas          1067
1475    2016        Klaipėdos miestas          3731
1476    2016          Alytaus miestas           871
1477    2016        Klaipėdos rajonas           705
1478    2016        Kretingos rajonas           393
1479    2016         Kupiškio rajonas           370
1480    2016          Lazdijų rajonas           344
1481    2016          Marijampolės PK          1087
1482    2016         Mažeikių rajonas           725
1483    2016           Molėtų rajonas           237
1484    2016                  Neringa            60
1485    2016      Pagėgių savivaldybė           171
1486    2016         Pakruojo rajonas           425
1487    2016         Anykščių rajonas           406
1488    2016                  Palanga           425
1489    2016        Panevėžio miestas          2068
1490    2016        Panevėžio rajonas           588
1491    2016         Pasvalio rajonas           397
1492    2016          Plungės rajonas           513
1493    2016           Prienų rajonas           468
1494    2016      Radviliškio rajonas           738
1495    2016         Raseinių rajonas           600
1496    2016      Rietavo savivaldybė           102
1497    2016         Rokiškio rajonas           602
1498    2016                Birštonas            47
1499    2016           Skuodo rajonas           189
1500    2016            Šakių rajonas           415
1501    2016       Šalčininkų rajonas           732
1502    2016          Šiaulių miestas          1925
1503    2016          Šiaulių rajonas           660
1504    2016          Šilalės rajonas           271
1505    2016          Šilutės rajonas           734
1506    2016         Širvintų rajonas           206
1507    2016       Švenčionių rajonas           325
1508    2016         Tauragės rajonas           478
1509    2016            Biržų rajonas           555
1510    2016           Telšių rajonas           674
1511    2016            Trakų rajonas           503
1512    2016         Ukmergės rajonas           503
1513    2016           Utenos rajonas           553
1514    2016          Varėnos rajonas           386
1515    2016      Vilkaviškio rajonas           648
1516    2016         Vilniaus miestas         13357
1517    2016         Vilniaus rajonas          1631
1518    2016                Visaginas           213
1519    2016           Zarasų rajonas           191
1520    2016             Druskininkai           265
1521    2016          Alytaus rajonas           373
1522    2016               Elektrėnai           360
1523    2016        Ignalinos rajonas           187
1524    2016          Jonavos rajonas           893
1525    2017               Respublika         60363
1526    2017          Akmenės rajonas           375
1527    2017         Joniškio rajonas           408
1528    2017         Jurbarko rajonas           521
1529    2017      Kaišiadorių rajonas           813
1530    2017   Kalvarijos savivaldybė           335
1531    2017            Kauno miestas          8009
1532    2017            Kauno rajonas          1894
1533    2017  Kazlų Rūdos savivaldybė           237
1534    2017           Kelmės rajonas           511
1535    2017         Kėdainių rajonas          1123
1536    2017        Klaipėdos miestas          4130
1537    2017          Alytaus miestas           776
1538    2017        Klaipėdos rajonas           762
1539    2017        Kretingos rajonas           417
1540    2017         Kupiškio rajonas           409
1541    2017          Lazdijų rajonas           364
1542    2017          Marijampolės PK          1062
1543    2017         Mažeikių rajonas           876
1544    2017           Molėtų rajonas           349
1545    2017                  Neringa            46
1546    2017      Pagėgių savivaldybė           119
1547    2017         Pakruojo rajonas           471
1548    2017         Anykščių rajonas           502
1549    2017                  Palanga           429
1550    2017        Panevėžio miestas          1805
1551    2017        Panevėžio rajonas           611
1552    2017         Pasvalio rajonas           637
1553    2017          Plungės rajonas           530
1554    2017           Prienų rajonas           547
1555    2017      Radviliškio rajonas           731
1556    2017         Raseinių rajonas           594
1557    2017      Rietavo savivaldybė            85
1558    2017         Rokiškio rajonas           604
1559    2017                Birštonas            67
1560    2017           Skuodo rajonas           196
1561    2017            Šakių rajonas           500
1562    2017       Šalčininkų rajonas           745
1563    2017          Šiaulių miestas          2013
1564    2017          Šiaulių rajonas           700
1565    2017          Šilalės rajonas           329
1566    2017          Šilutės rajonas           720
1567    2017         Širvintų rajonas           234
1568    2017       Švenčionių rajonas           387
1569    2017         Tauragės rajonas           536
1570    2017            Biržų rajonas           639
1571    2017           Telšių rajonas           719
1572    2017            Trakų rajonas           594
1573    2017         Ukmergės rajonas           578
1574    2017           Utenos rajonas           731
1575    2017          Varėnos rajonas           434
1576    2017      Vilkaviškio rajonas           639
1577    2017         Vilniaus miestas         13434
1578    2017         Vilniaus rajonas          1944
1579    2017                Visaginas           326
1580    2017           Zarasų rajonas           328
1581    2017             Druskininkai           300
1582    2017          Alytaus rajonas           371
1583    2017               Elektrėnai           433
1584    2017        Ignalinos rajonas           348
1585    2017          Jonavos rajonas          1036
1594    2007               Respublika         67990
1606    2007          Akmenės rajonas           316
1618    2007         Joniškio rajonas           359
1630    2007         Jurbarko rajonas           477
1642    2007      Kaišiadorių rajonas           801
1654    2007   Kalvarijos savivaldybė           326
1666    2007            Kauno miestas          8382
1678    2007            Kauno rajonas          1423
1690    2007  Kazlų Rūdos savivaldybė           178
1702    2007           Kelmės rajonas           363
1714    2007         Kėdainių rajonas          1038
1726    2007        Klaipėdos miestas          5167
1738    2007          Alytaus miestas           872
1750    2007        Klaipėdos rajonas           793
1762    2007        Kretingos rajonas           410
1774    2007         Kupiškio rajonas           261
1786    2007          Lazdijų rajonas           306
1798    2007          Marijampolės PK          1043
1810    2007         Mažeikių rajonas           660
1822    2007           Molėtų rajonas           236
1834    2007                  Neringa            41
1846    2007      Pagėgių savivaldybė           264
1858    2007         Pakruojo rajonas           411
1870    2007         Anykščių rajonas           489
1882    2007                  Palanga           558
1894    2007        Panevėžio miestas          2242
1906    2007        Panevėžio rajonas           843
1918    2007         Pasvalio rajonas           413
1930    2007          Plungės rajonas           679
1942    2007           Prienų rajonas           421
1954    2007      Radviliškio rajonas           738
1966    2007         Raseinių rajonas           477
1978    2007      Rietavo savivaldybė            86
1990    2007         Rokiškio rajonas           433
2002    2007                Birštonas            47
2014    2007           Skuodo rajonas           172
2026    2007            Šakių rajonas           425
2038    2007       Šalčininkų rajonas           486
2050    2007          Šiaulių miestas          2736
2062    2007          Šiaulių rajonas           512
2074    2007          Šilalės rajonas           293
2086    2007          Šilutės rajonas           850
2098    2007         Širvintų rajonas           305
2110    2007       Švenčionių rajonas           295
2122    2007         Tauragės rajonas           736
2134    2007            Biržų rajonas           449
2146    2007           Telšių rajonas           643
2158    2007            Trakų rajonas           408
2170    2007         Ukmergės rajonas           678
2182    2007           Utenos rajonas           701
2194    2007          Varėnos rajonas           415
2206    2007      Vilkaviškio rajonas           728
2218    2007         Vilniaus miestas         20455
2230    2007         Vilniaus rajonas          1968
2242    2007                Visaginas           507
2254    2007           Zarasų rajonas           270
2266    2007             Druskininkai           340
2278    2007          Alytaus rajonas           300
2290    2007               Elektrėnai           310
2302    2007        Ignalinos rajonas           292
2314    2007          Jonavos rajonas          1163
2326    2013               Respublika         77373
2338    2013          Akmenės rajonas           497
2350    2013         Joniškio rajonas           903
2362    2013         Jurbarko rajonas           665
2374    2013      Kaišiadorių rajonas           664
2386    2013   Kalvarijos savivaldybė           411
2398    2013            Kauno miestas          8759
2410    2013            Kauno rajonas          1766
2422    2013  Kazlų Rūdos savivaldybė           223
2434    2013           Kelmės rajonas           589
2446    2013         Kėdainių rajonas          1112
2458    2013        Klaipėdos miestas          5795
2470    2013          Alytaus miestas          1306
2482    2013        Klaipėdos rajonas           969
2494    2013        Kretingos rajonas           445
2506    2013         Kupiškio rajonas           442
2518    2013          Lazdijų rajonas           551
2530    2013          Marijampolės PK          1753
2542    2013         Mažeikių rajonas          1330
2554    2013           Molėtų rajonas           295
2566    2013                  Neringa            41
2578    2013      Pagėgių savivaldybė           316
2590    2013         Pakruojo rajonas           839
2602    2013         Anykščių rajonas           562
2614    2013                  Palanga           483
2626    2013        Panevėžio miestas          2025
2638    2013        Panevėžio rajonas           825
2650    2013         Pasvalio rajonas           653
2662    2013          Plungės rajonas           682
2674    2013           Prienų rajonas           730
2686    2013      Radviliškio rajonas          1261
2698    2013         Raseinių rajonas          1049
2710    2013      Rietavo savivaldybė           145
2722    2013         Rokiškio rajonas           664
2734    2013                Birštonas            60
2746    2013           Skuodo rajonas           214
2758    2013            Šakių rajonas           546
2770    2013       Šalčininkų rajonas          1011
2782    2013          Šiaulių miestas          3046
2794    2013          Šiaulių rajonas          1078
2806    2013          Šilalės rajonas           488
2818    2013          Šilutės rajonas          1360
2830    2013         Širvintų rajonas           334
2842    2013       Švenčionių rajonas           371
2854    2013         Tauragės rajonas          1025
2866    2013            Biržų rajonas           610
2878    2013           Telšių rajonas           980
2890    2013            Trakų rajonas           748
2902    2013         Ukmergės rajonas           868
2914    2013           Utenos rajonas          1010
2926    2013          Varėnos rajonas           488
2938    2013      Vilkaviškio rajonas           860
2950    2013         Vilniaus miestas         17054
2962    2013         Vilniaus rajonas          2900
2974    2013                Visaginas           385
2986    2013           Zarasų rajonas           332
2998    2013             Druskininkai           368
3010    2013          Alytaus rajonas           491
3022    2013               Elektrėnai           577
3034    2013        Ignalinos rajonas           444
3046    2013          Jonavos rajonas           975
3058    2012               Respublika         75349
3070    2012          Akmenės rajonas           536
3082    2012         Joniškio rajonas           672
3094    2012         Jurbarko rajonas           546
3106    2012      Kaišiadorių rajonas           641
3118    2012   Kalvarijos savivaldybė           287
3130    2012            Kauno miestas          7778
3142    2012            Kauno rajonas          1681
3154    2012  Kazlų Rūdos savivaldybė           199
3166    2012           Kelmės rajonas           525
3178    2012         Kėdainių rajonas          1090
3190    2012        Klaipėdos miestas          4647
3202    2012          Alytaus miestas          1200
3214    2012        Klaipėdos rajonas           965
3226    2012        Kretingos rajonas           398
3238    2012         Kupiškio rajonas           452
3250    2012          Lazdijų rajonas           539

In [12]:
# Sujungti Alytaus miestas ir Alytaus rajonas eilutes
alytus = nusikalstamumas_metais[nusikalstamumas_metais['Savivaldybė'].isin(['Alytaus miestas', 'Alytaus rajonas'])]

numeric_cols = ['Nusikaltimai']

# Apskaiciuoti skaitines reikšmes, pirmą ne-skaitinę reikšmę palikti kitiems stulpeliams
alytus_merged = alytus.groupby('Metai')[numeric_cols].sum().reset_index()
alytus_merged['Savivaldybė'] = 'Alytaus miestas ir rajonas'

# Pašalinti originalias Alytaus eilutes ir pridėti sujungtą
nusikalstamumas_metais = nusikalstamumas_metais[~nusikalstamumas_metais['Savivaldybė'].isin(['Alytaus miestas', 'Alytaus rajonas'])]
nusikalstamumas_metais = pd.concat([nusikalstamumas_metais, alytus_merged], ignore_index=True)

# Surūšiuoti
nusikalstamumas_metais = nusikalstamumas_metais.sort_values(['Metai', 'Savivaldybė']).reset_index(drop=True)

nusikalstamumas_metais

      Metai                 Savivaldybė  Nusikaltimai
0      2004             Akmenės rajonas           470
1      2004  Alytaus miestas ir rajonas          1504
2      2004            Anykščių rajonas           704
3      2004                   Birštonas            81
4      2004               Biržų rajonas           615
...     ...                         ...           ...
1315   2025             Šiaulių rajonas           434
1316   2025             Šilalės rajonas           150
1317   2025             Šilutės rajonas           478
1318   2025            Širvintų rajonas           143
1319   2025          Švenčionių rajonas           204

[1320 rows x 3 columns]

In [13]:
len(nusikalstamumas_metais['Savivaldybė'].unique())

60

In [14]:
nusikalstamumas_metais['Savivaldybė'].unique()

<ArrowStringArray>
[           'Akmenės rajonas', 'Alytaus miestas ir rajonas',
           'Anykščių rajonas',                  'Birštonas',
              'Biržų rajonas',               'Druskininkai',
                 'Elektrėnai',          'Ignalinos rajonas',
            'Jonavos rajonas',           'Joniškio rajonas',
           'Jurbarko rajonas',        'Kaišiadorių rajonas',
     'Kalvarijos savivaldybė',              'Kauno miestas',
              'Kauno rajonas',    'Kazlų Rūdos savivaldybė',
             'Kelmės rajonas',          'Klaipėdos miestas',
          'Klaipėdos rajonas',          'Kretingos rajonas',
           'Kupiškio rajonas',           'Kėdainių rajonas',
            'Lazdijų rajonas',            'Marijampolės PK',
           'Mažeikių rajonas',             'Molėtų rajonas',
                    'Neringa',        'Pagėgių savivaldybė',
           'Pakruojo rajonas',                    'Palanga',
          'Panevėžio miestas',          'Panevėžio rajonas',
           'Pasvalio rajonas',            'Plungės rajonas',
             'Prienų rajonas',        'Radviliškio rajonas',
           'Raseinių rajonas',                 'Respublika',
        'Rietavo savivaldybė',           'Rokiškio rajonas',
             'Skuodo rajonas',           'Tauragės rajonas',
             'Telšių rajonas',              'Trakų rajonas',
           'Ukmergės rajonas',             'Utenos rajonas',
            'Varėnos rajonas',        'Vilkaviškio rajonas',
           'Vilniaus miestas',           'Vilniaus rajonas',
                  'Visaginas',             'Zarasų rajonas',
              'Šakių rajonas',         'Šalčininkų rajonas',
            'Šiaulių miestas',            'Šiaulių rajonas',
            'Šilalės rajonas',            'Šilutės rajonas',
           'Širvintų rajonas',         'Švenčionių rajonas']
Length: 60, dtype: str

In [15]:
nusikalstamumas_metais = nusikalstamumas_metais[nusikalstamumas_metais['Savivaldybė'] != 'Respublika']

In [16]:
koordinates = {
    'Akmenės rajonas':              (56.2456, 22.7478),
    'Alytaus miestas ir rajonas':   (54.3963, 24.0457),
    'Anykščių rajonas':             (55.5167, 25.1000),
    'Birštonas':                    (54.6167, 24.0167),
    'Biržų rajonas':                (56.2000, 24.7500),
    'Druskininkai':                 (53.9833, 23.9833),
    'Elektrėnai':                   (54.7833, 24.6667),
    'Ignalinos rajonas':            (55.3500, 26.1667),
    'Jonavos rajonas':              (55.0667, 24.2833),
    'Joniškio rajonas':             (56.2333, 23.6167),
    'Jurbarko rajonas':             (55.0833, 22.7667),
    'Kaišiadorių rajonas':          (54.8667, 24.4500),
    'Kalvarijos savivaldybė':       (54.4167, 23.2167),
    'Kauno miestas':                (54.8985, 23.9036),
    'Kauno rajonas':                (54.9000, 23.8000),
    'Kazlų Rūdos savivaldybė':      (54.7500, 23.5000),
    'Kelmės rajonas':               (55.6333, 22.9333),
    'Klaipėdos miestas':            (55.7033, 21.1442),
    'Klaipėdos rajonas':            (55.6500, 21.3000),
    'Kretingos rajonas':            (55.8833, 21.2333),
    'Kupiškio rajonas':             (55.8333, 24.9667),
    'Kėdainių rajonas':             (55.2833, 23.9833),
    'Lazdijų rajonas':              (54.2333, 23.5167),
    'Marijampolės PK':              (54.5594, 23.3544),
    'Mažeikių rajonas':             (56.3167, 22.3333),
    'Molėtų rajonas':               (55.2333, 25.4167),
    'Neringa':                      (55.4667, 21.0833),
    'Pagėgių savivaldybė':          (55.1333, 21.9000),
    'Pakruojo rajonas':             (56.0667, 23.8667),
    'Palanga':                      (55.9167, 21.0667),
    'Panevėžio miestas':            (55.7333, 24.3667),
    'Panevėžio rajonas':            (55.7000, 24.3333),
    'Pasvalio rajonas':             (56.0600, 24.4033),
    'Plungės rajonas':              (55.9167, 21.8500),
    'Prienų rajonas':               (54.6333, 23.9500),
    'Radviliškio rajonas':          (55.8000, 23.5333),
    'Raseinių rajonas':             (55.3667, 23.1167),
    #'Respublika':                   (55.1694, 23.8813),  # Lietuvos centras
    'Rietavo savivaldybė':          (55.7333, 21.9167),
    'Rokiškio rajonas':             (55.9667, 25.5833),
    'Skuodo rajonas':               (56.2667, 21.5333),
    'Tauragės rajonas':             (55.2500, 22.2833),
    'Telšių rajonas':               (55.9833, 22.3500),
    'Trakų rajonas':                (54.6333, 24.9333),
    'Ukmergės rajonas':             (55.2500, 24.7667),
    'Utenos rajonas':               (55.5000, 25.6000),
    'Varėnos rajonas':              (54.2167, 24.5667),
    'Vilkaviškio rajonas':          (54.6500, 23.0333),
    'Vilniaus miestas':             (54.6872, 25.2797),
    'Vilniaus rajonas':             (54.8000, 25.5000),
    'Visaginas':                    (55.6000, 26.4333),
    'Zarasų rajonas':               (55.7333, 26.2500),
    'Šakių rajonas':                (54.9500, 23.0500),
    'Šalčininkų rajonas':           (54.3167, 25.3833),
    'Šiaulių miestas':              (55.9333, 23.3167),
    'Šiaulių rajonas':              (55.8667, 23.1833),
    'Šilalės rajonas':              (55.4833, 22.1833),
    'Šilutės rajonas':              (55.3500, 21.4667),
    'Širvintų rajonas':             (55.0500, 24.9500),
    'Švenčionių rajonas':           (55.1333, 26.0000),
}

nusikalstamumas_metais['lat'] = nusikalstamumas_metais['Savivaldybė'].map(lambda x: koordinates[x][0])
nusikalstamumas_metais['lon'] = nusikalstamumas_metais['Savivaldybė'].map(lambda x: koordinates[x][1])
nusikalstamumas_metais

      Metai                 Savivaldybė  Nusikaltimai      lat      lon
0      2004             Akmenės rajonas           470  56.2456  22.7478
1      2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2      2004            Anykščių rajonas           704  55.5167  25.1000
3      2004                   Birštonas            81  54.6167  24.0167
4      2004               Biržų rajonas           615  56.2000  24.7500
...     ...                         ...           ...      ...      ...
1315   2025             Šiaulių rajonas           434  55.8667  23.1833
1316   2025             Šilalės rajonas           150  55.4833  22.1833
1317   2025             Šilutės rajonas           478  55.3500  21.4667
1318   2025            Širvintų rajonas           143  55.0500  24.9500
1319   2025          Švenčionių rajonas           204  55.1333  26.0000

[1298 rows x 5 columns]

In [17]:
nusikalstamumas_metais.columns.tolist()

['Metai', 'Savivaldybė', 'Nusikaltimai', 'lat', 'lon']

# Pridedame kitas statistikas

In [18]:
from thefuzz import process

def match_savivaldybes(df_main, df_new, col_main='Savivaldybė', col_new='Savivaldybė'):
    """Automatiškai suranda geriausią pavadinimo atitikmenį"""
    unique_main = df_main[col_main].unique()
    unique_new = df_new[col_new].unique()

    matches = {}
    for name in unique_new:
        best_match, score = process.extractOne(name, unique_main)
        matches[name] = (best_match, score)

    return pd.DataFrame([
        {'Originalus': k, 'Surastas': v[0], 'Tikslumas': v[1]}
        for k, v in matches.items()
    ]).sort_values('Tikslumas')

In [19]:
def sujungimas(df, failas, stulpelio_pav):
    rod = pd.read_csv(f"statistikoa savivaldybem/{failas}")

    rod = rod.rename(
        columns={"Administracinė teritorija": "Savivaldybė"}
    )

    rod = rod.rename(
        columns={"Laikotarpis": "Metai"}
    )

    rod = rod[['Savivaldybė', 'Reikšmė', 'Metai']]

    rod['Savivaldybė'] = rod['Savivaldybė'].replace({
    'Alytaus m. sav.': 'Alytaus sav.',
    'Alytaus r. sav.': 'Alytaus sav.'
    })

    rod['Reikšmė'] = rod.groupby(['Savivaldybė', 'Metai'])['Reikšmė'].transform('mean')
    rod = rod.drop_duplicates(subset=['Savivaldybė', 'Metai'])

    match_df = match_savivaldybes(df, rod)
    print(match_df.to_string())

    manual_fixes = {
    'Vilniaus r. sav.': 'Vilniaus rajonas',
    'Kauno r. sav.':    'Kauno rajonas',
    "Klaipėdos r. sav.": 'Klaipėdos rajonas',
    "Panevėžio r. sav.": "Panevėžio rajonas",
    "Šiaulių r. sav.": "Šiaulių rajonas",

}

    # Sukurti pilną mapping
    mapping = {row['Originalus']: row['Surastas'] for _, row in match_df.iterrows()}
    mapping.update(manual_fixes)  # rankiniai pataisymai perrašo automatinius

    # Pritaikyti
    rod['Savivaldybė'] = rod['Savivaldybė'].map(mapping)

    print()
    print("---------PATIKTINTI AR LIKO NA------------")
    # Patikrinti ar liko NaN (nerasti atitikmenys)
    print(rod[rod['Savivaldybė'].isna()])
    print()

    print(rod[rod.isnull().any(axis=1)].to_string())
    rod = rod.dropna()

    df = df.merge(
    rod.rename(columns={'Reikšmė': stulpelio_pav}),
    on=['Savivaldybė', 'Metai'],
    how='left'
)
    print()
    print("---------SUJUNGTAS------------")
    print(df.shape)
    print(df.head(10))

    return df

## Gyventojų skaičius

In [20]:
df = sujungimas(nusikalstamumas_metais, 'Gyventoju_tankis_vienam_km2.csv', "Gyventoju_tankis")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 6)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis
0             34.30
1            886.95
2             19.10
3             42.30
4             23.20
5             54.30
6             55.00
7             14.70
8             54.60
9             26.90

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10
3,2004,Birštonas,81,54.6167,24.0167,42.30
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20
...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70

## Bedarbių skaičius

In [21]:
df = sujungimas(df, 'bedarbiu_skaicius.csv', "Bedarbiu_sk")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006

---------SUJUNGTAS------------
(1298, 7)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk
0             34.30       2770.0
1            886.95       2490.5
2             19.10       1017.0
3             42.30        139.0
4             23.20       1592.0
5             54.30       2183.0
6             55.00        426.0
7             14.70       1501.0
8             54.60       3282.0
9             26.90       2240.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0
...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0

# Imigrantų skaičius

In [22]:
df = sujungimas(df, 'imigrantu_skaicius.csv', "Imigrantu_sk")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 8)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk
0             34.30       2770.0          66.0
1            886.95       2490.5          71.0
2             19.10       1017.0          14.0
3             42.30        139.0           9.0
4             23.20       1592.0          24.0
5             54.30       2183.0          48.0
6             55.00        426.0          26.0
7             14.70       1501.0          30.0
8             54.60       3282.0         159.0
9             26.90       2240.0          31.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0
...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0

# Medianinis gyventojų amžius

In [23]:
df = sujungimas(df, 'medianinis_gyventoju_amzius.csv', "Medianinis_amzius")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 9)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius
0             34.30       2770.0          66.0               37.0
1            886.95       2490.5          71.0               38.5
2             19.10       1017.0          14.0               42.0
3             42.30        139.0           9.0               40.0
4             23.20       1592.0          24.0               39.0
5             54.30       2183.0          48.0               39.0
6             55.00        426.0          26.0               38.0
7             14.70       1501.0          30.0               43.0
8             54.60       3282.0         159.0               35.0
9             26.90       2240.0          31.0               37.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0
...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0

## Moterų skaičius tenkantis vienam tūkstančiui vyrų

In [24]:
df = sujungimas(df, 'moteru_skaicius_tenkantis_tukstanciui_vyru.csv', "Moteru")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 10)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0
...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0

## Nefinansinių įmonių apyvarta

In [25]:
df = sujungimas(df, 'nefinansiniu_imoniu_apyvarta.csv', "Apyvarta")
df

             Originalus                    Surastas  Tikslumas
4         Trakų r. sav.               Trakų rajonas         64
32        Biržų r. sav.               Biržų rajonas         64
30        Šakių r. sav.               Šakių rajonas         64
16        Kauno r. sav.               Kauno miestas         64
58       Zarasų r. sav.              Zarasų rajonas         67
40       Kelmės r. sav.              Kelmės rajonas         67
56       Utenos r. sav.              Utenos rajonas         67
55       Molėtų r. sav.              Molėtų rajonas         67
25       Skuodo r. sav.              Skuodo rajonas         67
52       Telšių r. sav.              Telšių rajonas         67
18       Prienų r. sav.              Prienų rajonas         67
44      Šiaulių r. sav.             Šiaulių miestas         69
38      Akmenės r. sav.             Akmenės rajonas         69
50      Plungės r. sav.             Plungės rajonas         69
26      Šilutės r. sav.             Šilutės rajonas         69
47      Šilalės r. sav.             Šilalės rajonas         69
13      Jonavos r. sav.             Jonavos rajonas         69
11      Varėnos r. sav.             Varėnos rajonas         69
10      Lazdijų r. sav.             Lazdijų rajonas         69
53     Anykščių r. sav.            Anykščių rajonas         71
39     Joniškio r. sav.            Joniškio rajonas         71
37     Rokiškio r. sav.            Rokiškio rajonas         71
36     Pasvalio r. sav.            Pasvalio rajonas         71
48     Tauragės r. sav.            Tauragės rajonas         71
33     Kupiškio r. sav.            Kupiškio rajonas         71
5      Ukmergės r. sav.            Ukmergės rajonas         71
2      Širvintų r. sav.            Širvintų rajonas         71
49     Mažeikių r. sav.            Mažeikių rajonas         71
45     Jurbarko r. sav.            Jurbarko rajonas         71
19     Raseinių r. sav.            Raseinių rajonas         71
17     Kėdainių r. sav.            Kėdainių rajonas         71
7      Vilniaus r. sav.            Vilniaus miestas         71
41     Pakruojo r. sav.            Pakruojo rajonas         71
15        Kauno m. sav.               Kauno miestas         72
22    Kretingos r. sav.           Kretingos rajonas         73
21    Klaipėdos r. sav.           Klaipėdos miestas         73
35    Panevėžio r. sav.           Panevėžio miestas         73
54    Ignalinos r. sav.           Ignalinos rajonas         73
1    Šalčininkų r. sav.          Šalčininkų rajonas         74
3    Švenčionių r. sav.          Švenčionių rajonas         74
43      Šiaulių m. sav.             Šiaulių miestas         76
42  Radviliškio r. sav.         Radviliškio rajonas         76
14  Kaišiadorių r. sav.         Kaišiadorių rajonas         76
57        Visagino sav.                   Visaginas         76
12        Birštono sav.                   Birštonas         76
31  Vilkaviškio r. sav.         Vilkaviškio rajonas         76
6      Vilniaus m. sav.            Vilniaus miestas         77
0        Elektrėnų sav.                  Elektrėnai         78
34    Panevėžio m. sav.           Panevėžio miestas         79
20    Klaipėdos m. sav.           Klaipėdos miestas         79
9      Druskininkų sav.                Druskininkai         81
24     Palangos m. sav.                     Palanga         83
23        Neringos sav.                     Neringa         83
29    Marijampolės sav.             Marijampolės PK         84
8          Alytaus sav.  Alytaus miestas ir rajonas         86
28     Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27      Kalvarijos sav.      Kalvarijos savivaldybė         90
51         Rietavo sav.         Rietavo savivaldybė         90
46         Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

---------SUJUNGTAS------------
(1298, 11)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN

## Policijos pareigūnų skaičius

In [26]:
df = sujungimas(df, 'policijos_pareigunu_skaicius.csv', "Policija")
df

             Originalus                    Surastas  Tikslumas
4         Trakų r. sav.               Trakų rajonas         64
32        Biržų r. sav.               Biržų rajonas         64
30        Šakių r. sav.               Šakių rajonas         64
16        Kauno r. sav.               Kauno miestas         64
58       Zarasų r. sav.              Zarasų rajonas         67
40       Kelmės r. sav.              Kelmės rajonas         67
56       Utenos r. sav.              Utenos rajonas         67
55       Molėtų r. sav.              Molėtų rajonas         67
25       Skuodo r. sav.              Skuodo rajonas         67
52       Telšių r. sav.              Telšių rajonas         67
18       Prienų r. sav.              Prienų rajonas         67
44      Šiaulių r. sav.             Šiaulių miestas         69
38      Akmenės r. sav.             Akmenės rajonas         69
50      Plungės r. sav.             Plungės rajonas         69
26      Šilutės r. sav.             Šilutės rajonas         69
47      Šilalės r. sav.             Šilalės rajonas         69
13      Jonavos r. sav.             Jonavos rajonas         69
11      Varėnos r. sav.             Varėnos rajonas         69
10      Lazdijų r. sav.             Lazdijų rajonas         69
53     Anykščių r. sav.            Anykščių rajonas         71
39     Joniškio r. sav.            Joniškio rajonas         71
37     Rokiškio r. sav.            Rokiškio rajonas         71
36     Pasvalio r. sav.            Pasvalio rajonas         71
48     Tauragės r. sav.            Tauragės rajonas         71
33     Kupiškio r. sav.            Kupiškio rajonas         71
5      Ukmergės r. sav.            Ukmergės rajonas         71
2      Širvintų r. sav.            Širvintų rajonas         71
49     Mažeikių r. sav.            Mažeikių rajonas         71
45     Jurbarko r. sav.            Jurbarko rajonas         71
19     Raseinių r. sav.            Raseinių rajonas         71
17     Kėdainių r. sav.            Kėdainių rajonas         71
7      Vilniaus r. sav.            Vilniaus miestas         71
41     Pakruojo r. sav.            Pakruojo rajonas         71
15        Kauno m. sav.               Kauno miestas         72
22    Kretingos r. sav.           Kretingos rajonas         73
21    Klaipėdos r. sav.           Klaipėdos miestas         73
35    Panevėžio r. sav.           Panevėžio miestas         73
54    Ignalinos r. sav.           Ignalinos rajonas         73
1    Šalčininkų r. sav.          Šalčininkų rajonas         74
3    Švenčionių r. sav.          Švenčionių rajonas         74
43      Šiaulių m. sav.             Šiaulių miestas         76
42  Radviliškio r. sav.         Radviliškio rajonas         76
14  Kaišiadorių r. sav.         Kaišiadorių rajonas         76
57        Visagino sav.                   Visaginas         76
12        Birštono sav.                   Birštonas         76
31  Vilkaviškio r. sav.         Vilkaviškio rajonas         76
6      Vilniaus m. sav.            Vilniaus miestas         77
0        Elektrėnų sav.                  Elektrėnai         78
34    Panevėžio m. sav.           Panevėžio miestas         79
20    Klaipėdos m. sav.           Klaipėdos miestas         79
9      Druskininkų sav.                Druskininkai         81
24     Palangos m. sav.                     Palanga         83
23        Neringos sav.                     Neringa         83
29    Marijampolės sav.             Marijampolės PK         84
8          Alytaus sav.  Alytaus miestas ir rajonas         86
28     Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27      Kalvarijos sav.      Kalvarijos savivaldybė         90
51         Rietavo sav.         Rietavo savivaldybė         90
46         Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

---------SUJUNGTAS------------
(1298, 12)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija
0       NaN      69.0
1       NaN     355.0
2       NaN      78.0
3       NaN      22.0
4       NaN      84.0
5       NaN      78.0
6       NaN      64.0
7       NaN      65.0
8       NaN     125.0
9       NaN      83.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN

## Skurdo rizikos lygis

In [27]:
df = sujungimas(df, 'skurdo_rizikos_lygis_nuo_2010.csv', "Skurdas")
df

             Originalus                    Surastas  Tikslumas
4         Trakų r. sav.               Trakų rajonas         64
32        Biržų r. sav.               Biržų rajonas         64
30        Šakių r. sav.               Šakių rajonas         64
16        Kauno r. sav.               Kauno miestas         64
58       Zarasų r. sav.              Zarasų rajonas         67
40       Kelmės r. sav.              Kelmės rajonas         67
56       Utenos r. sav.              Utenos rajonas         67
55       Molėtų r. sav.              Molėtų rajonas         67
25       Skuodo r. sav.              Skuodo rajonas         67
52       Telšių r. sav.              Telšių rajonas         67
18       Prienų r. sav.              Prienų rajonas         67
44      Šiaulių r. sav.             Šiaulių miestas         69
38      Akmenės r. sav.             Akmenės rajonas         69
50      Plungės r. sav.             Plungės rajonas         69
26      Šilutės r. sav.             Šilutės rajonas         69
47      Šilalės r. sav.             Šilalės rajonas         69
13      Jonavos r. sav.             Jonavos rajonas         69
11      Varėnos r. sav.             Varėnos rajonas         69
10      Lazdijų r. sav.             Lazdijų rajonas         69
53     Anykščių r. sav.            Anykščių rajonas         71
39     Joniškio r. sav.            Joniškio rajonas         71
37     Rokiškio r. sav.            Rokiškio rajonas         71
36     Pasvalio r. sav.            Pasvalio rajonas         71
48     Tauragės r. sav.            Tauragės rajonas         71
33     Kupiškio r. sav.            Kupiškio rajonas         71
5      Ukmergės r. sav.            Ukmergės rajonas         71
2      Širvintų r. sav.            Širvintų rajonas         71
49     Mažeikių r. sav.            Mažeikių rajonas         71
45     Jurbarko r. sav.            Jurbarko rajonas         71
19     Raseinių r. sav.            Raseinių rajonas         71
17     Kėdainių r. sav.            Kėdainių rajonas         71
7      Vilniaus r. sav.            Vilniaus miestas         71
41     Pakruojo r. sav.            Pakruojo rajonas         71
15        Kauno m. sav.               Kauno miestas         72
22    Kretingos r. sav.           Kretingos rajonas         73
21    Klaipėdos r. sav.           Klaipėdos miestas         73
35    Panevėžio r. sav.           Panevėžio miestas         73
54    Ignalinos r. sav.           Ignalinos rajonas         73
1    Šalčininkų r. sav.          Šalčininkų rajonas         74
3    Švenčionių r. sav.          Švenčionių rajonas         74
43      Šiaulių m. sav.             Šiaulių miestas         76
42  Radviliškio r. sav.         Radviliškio rajonas         76
14  Kaišiadorių r. sav.         Kaišiadorių rajonas         76
57        Visagino sav.                   Visaginas         76
12        Birštono sav.                   Birštonas         76
31  Vilkaviškio r. sav.         Vilkaviškio rajonas         76
6      Vilniaus m. sav.            Vilniaus miestas         77
0        Elektrėnų sav.                  Elektrėnai         78
34    Panevėžio m. sav.           Panevėžio miestas         79
20    Klaipėdos m. sav.           Klaipėdos miestas         79
9      Druskininkų sav.                Druskininkai         81
24     Palangos m. sav.                     Palanga         83
23        Neringos sav.                     Neringa         83
29    Marijampolės sav.             Marijampolės PK         84
8          Alytaus sav.  Alytaus miestas ir rajonas         86
28     Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27      Kalvarijos sav.      Kalvarijos savivaldybė         90
51         Rietavo sav.         Rietavo savivaldybė         90
46         Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

---------SUJUNGTAS------------
(1298, 13)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija  Skurdas
0       NaN      69.0      NaN
1       NaN     355.0      NaN
2       NaN      78.0      NaN
3       NaN      22.0      NaN
4       NaN      84.0      NaN
5       NaN      78.0      NaN
6       NaN      64.0      NaN
7       NaN      65.0      NaN
8       NaN     125.0      NaN
9       NaN      83.0      NaN

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4

## Socialinę pašalpą gaunatys

In [28]:
df = sujungimas(df, 'socialine_pasalpa_gaunanciu_asmenu_skaicius.csv', "Pasalpa_gaunantys")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 14)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija  Skurdas  Pasalpa_gaunantys
0       NaN      69.0      NaN             1557.0
1       NaN     355.0      NaN             1071.5
2       NaN      78.0      NaN             1115.0
3       NaN      22.0      NaN              143.0
4       NaN      84.0      NaN             1111.0
5       NaN      78.0      NaN             1186.0
6       NaN      64.0      NaN              349.0
7       NaN      65.0      NaN              991.0
8       NaN     125.0      NaN             2417.0
9       NaN      83.0      NaN             1721.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0

## Gyventojų skaičius

In [29]:
df = sujungimas(df, 'gyventoju_skaicius.csv', "gyventoju_skaicius")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
682  Marijampolės PK      NaN   2004
683  Marijampolės PK      NaN   2005
684  Marijampolės PK      NaN   2006
685  Marijampolės PK      NaN   2007
686  Marijampolės PK      NaN   2008
687  Marijampolės PK      NaN   2009
688  Marijampolės PK      NaN   2010
689  Marijampolės PK      NaN   2011
690  Marijampolės PK      NaN   2012
691  Marijampolės PK      NaN   2013
692  Marijampolės PK      NaN   2014
693  Marijampolės PK      NaN   2015
694  Marijampolės PK      NaN   2016
695  Marijampolės PK      NaN   2017
696  Marijampolės PK      NaN   2018
697  Marijampolės PK      NaN   2019
698  Marijampolės PK      NaN   2020
699  Marijampolės PK      NaN   2021
700  Marijampolės PK      NaN   2022
701  Marijampolės PK      NaN   2023
702  Marijampolės PK      NaN   2024
703  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 15)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija  Skurdas  Pasalpa_gaunantys  gyventoju_skaicius
0       NaN      69.0      NaN             1557.0             28951.0
1       NaN     355.0      NaN             1071.5             50897.0
2       NaN      78.0      NaN             1115.0             33783.0
3       NaN      22.0      NaN              143.0              5240.0
4       NaN      84.0      NaN             1111.0             34266.0
5       NaN      78.0      NaN             1186.0             24665.0
6       NaN      64.0      NaN              349.0             28015.0
7       NaN      65.0      NaN              991.0             21944.0
8       NaN     125.0      NaN             2417.0             51510.0
9       NaN      83.0      NaN             1721.0             31012.0

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0

## Vaikai nesimokantys mokykloje

In [30]:
vaikai = pd.read_csv('statistikoa savivaldybem/Vaikai_nesimokantys_mokykloje_nors_turetu_nuo_2009.csv')

vaikai['Laikotarpis'] = vaikai['Laikotarpis'].str.split('-').str[1]

vaikai.to_csv("statistikoa savivaldybem/Vaikai_nesimokantys_mokykloje_nors_turetu_nuo_2009_pakeista.csv", index=False)

df = sujungimas(df, 'Vaikai_nesimokantys_mokykloje_nors_turetu_nuo_2009_pakeista.csv', "Vaikai_nesimokantys")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
496  Marijampolės PK      NaN   2010
497  Marijampolės PK      NaN   2011
498  Marijampolės PK      NaN   2012
499  Marijampolės PK      NaN   2013
500  Marijampolės PK      NaN   2014
501  Marijampolės PK      NaN   2015
502  Marijampolės PK      NaN   2016
503  Marijampolės PK      NaN   2017
504  Marijampolės PK      NaN   2018
505  Marijampolės PK      NaN   2019
506  Marijampolės PK      NaN   2020
507  Marijampolės PK      NaN   2021
508  Marijampolės PK      NaN   2022
509  Marijampolės PK      NaN   2023
510  Marijampolės PK      NaN   2024
511  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 16)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija  Skurdas  Pasalpa_gaunantys  gyventoju_skaicius  \
0       NaN      69.0      NaN             1557.0             28951.0
1       NaN     355.0      NaN             1071.5             50897.0
2       NaN      78.0      NaN             1115.0             33783.0
3       NaN      22.0      NaN              143.0              5240.0
4       NaN      84.0      NaN             1111.0             34266.0
5       NaN      78.0      NaN             1186.0             24665.0
6       NaN      64.0      NaN              349.0             28015.0
7       NaN      65.0      NaN              991.0             21944.0
8       NaN     125.0      NaN             2417.0             51510.0
9       NaN      83.0      NaN             1721.0             31012.0

   Vaikai_nesimokantys
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius,Vaikai_nesimokantys
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0,NaN
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0,NaN
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0,NaN
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0,NaN
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0,115.0
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0,140.0
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0,361.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0,60.0
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0,65.0

## Vidutinis uždarbis

In [31]:
uzdarbis = pd.read_csv('statistikoa savivaldybem/vidutinis_menesinis_darbo_uzmokestis_bruto_nuo_2011.csv')

uzdarbis['Laikotarpis'] = uzdarbis['Laikotarpis'].str[:4]

uzdarbis.to_csv("statistikoa savivaldybem/vidutinis_menesinis_darbo_uzmokestis_bruto_nuo_2011_pakeista.csv", index=False)
uzdarbis

,Laikotarpis,Rodiklis,Tipas,Administracinė teritorija,Lytis,Sektorius,Matavimo vienetai,Reikšmė
0,2011,Darbo užmokestis (mėnesinis),Bruto,Elektrėnų sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,613.2
1,2012,Darbo užmokestis (mėnesinis),Bruto,Elektrėnų sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,637.2
2,2013,Darbo užmokestis (mėnesinis),Bruto,Elektrėnų sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,690.9
3,2014,Darbo užmokestis (mėnesinis),Bruto,Elektrėnų sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,668.7
4,2015,Darbo užmokestis (mėnesinis),Bruto,Elektrėnų sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,708.9
...,...,...,...,...,...,...,...,...
910,2021,Darbo užmokestis (mėnesinis),Bruto,Zarasų r. sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,1122.7
911,2022,Darbo užmokestis (mėnesinis),Bruto,Zarasų r. sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,1270.6
912,2023,Darbo užmokestis (mėnesinis),Bruto,Zarasų r. sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,1379.0
913,2024,Darbo užmokestis (mėnesinis),Bruto,Zarasų r. sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,1553.4
914,2025,Darbo užmokestis (mėnesinis),Bruto,Zarasų r. sav.,Vyrai ir moterys,Šalies ūkis su individualiosiomis įmonėmis,EUR,1804.6

In [32]:
df = sujungimas(df, 'vidutinis_menesinis_darbo_uzmokestis_bruto_nuo_2011_pakeista.csv', "Uzmokestis")
df

              Originalus                    Surastas  Tikslumas
31         Šakių r. sav.               Šakių rajonas         64
16         Kauno r. sav.               Kauno miestas         64
4          Trakų r. sav.               Trakų rajonas         64
33         Biržų r. sav.               Biržų rajonas         64
59        Zarasų r. sav.              Zarasų rajonas         67
18        Prienų r. sav.              Prienų rajonas         67
53        Telšių r. sav.              Telšių rajonas         67
56        Molėtų r. sav.              Molėtų rajonas         67
25        Skuodo r. sav.              Skuodo rajonas         67
41        Kelmės r. sav.              Kelmės rajonas         67
57        Utenos r. sav.              Utenos rajonas         67
45       Šiaulių r. sav.             Šiaulių miestas         69
26       Šilutės r. sav.             Šilutės rajonas         69
51       Plungės r. sav.             Plungės rajonas         69
39       Akmenės r. sav.             Akmenės rajonas         69
48       Šilalės r. sav.             Šilalės rajonas         69
13       Jonavos r. sav.             Jonavos rajonas         69
11       Varėnos r. sav.             Varėnos rajonas         69
10       Lazdijų r. sav.             Lazdijų rajonas         69
40      Joniškio r. sav.            Joniškio rajonas         71
42      Pakruojo r. sav.            Pakruojo rajonas         71
49      Tauragės r. sav.            Tauragės rajonas         71
50      Mažeikių r. sav.            Mažeikių rajonas         71
38      Rokiškio r. sav.            Rokiškio rajonas         71
34      Kupiškio r. sav.            Kupiškio rajonas         71
37      Pasvalio r. sav.            Pasvalio rajonas         71
54      Anykščių r. sav.            Anykščių rajonas         71
46      Jurbarko r. sav.            Jurbarko rajonas         71
2       Širvintų r. sav.            Širvintų rajonas         71
5       Ukmergės r. sav.            Ukmergės rajonas         71
19      Raseinių r. sav.            Raseinių rajonas         71
17      Kėdainių r. sav.            Kėdainių rajonas         71
7       Vilniaus r. sav.            Vilniaus miestas         71
15         Kauno m. sav.               Kauno miestas         72
22     Kretingos r. sav.           Kretingos rajonas         73
21     Klaipėdos r. sav.           Klaipėdos miestas         73
55     Ignalinos r. sav.           Ignalinos rajonas         73
36     Panevėžio r. sav.           Panevėžio miestas         73
3     Švenčionių r. sav.          Švenčionių rajonas         74
1     Šalčininkų r. sav.          Šalčininkų rajonas         74
14   Kaišiadorių r. sav.         Kaišiadorių rajonas         76
32   Vilkaviškio r. sav.         Vilkaviškio rajonas         76
58         Visagino sav.                   Visaginas         76
43   Radviliškio r. sav.         Radviliškio rajonas         76
44       Šiaulių m. sav.             Šiaulių miestas         76
12         Birštono sav.                   Birštonas         76
6       Vilniaus m. sav.            Vilniaus miestas         77
0         Elektrėnų sav.                  Elektrėnai         78
35     Panevėžio m. sav.           Panevėžio miestas         79
20     Klaipėdos m. sav.           Klaipėdos miestas         79
9       Druskininkų sav.                Druskininkai         81
24      Palangos m. sav.                     Palanga         83
23         Neringos sav.                     Neringa         83
30  Marijampolės r. sav.             Marijampolės PK         84
29     Marijampolės sav.             Marijampolės PK         84
8           Alytaus sav.  Alytaus miestas ir rajonas         86
28      Kazlų Rūdos sav.     Kazlų Rūdos savivaldybė         90
27       Kalvarijos sav.      Kalvarijos savivaldybė         90
52          Rietavo sav.         Rietavo savivaldybė         90
47          Pagėgių sav.         Pagėgių savivaldybė         90

---------PATIKTINTI AR LIKO NA------------
Empty DataFrame
Columns: [Savivaldybė, Reikšmė, Metai]
Index: []

         Savivaldybė  Reikšmė  Metai
465  Marijampolės PK      NaN   2011
466  Marijampolės PK      NaN   2012
467  Marijampolės PK      NaN   2013
468  Marijampolės PK      NaN   2014
469  Marijampolės PK      NaN   2015
470  Marijampolės PK      NaN   2016
471  Marijampolės PK      NaN   2017
472  Marijampolės PK      NaN   2018
473  Marijampolės PK      NaN   2019
474  Marijampolės PK      NaN   2020
475  Marijampolės PK      NaN   2021
476  Marijampolės PK      NaN   2022
477  Marijampolės PK      NaN   2023
478  Marijampolės PK      NaN   2024
479  Marijampolės PK      NaN   2025

---------SUJUNGTAS------------
(1298, 17)
   Metai                 Savivaldybė  Nusikaltimai      lat      lon  \
0   2004             Akmenės rajonas           470  56.2456  22.7478
1   2004  Alytaus miestas ir rajonas          1504  54.3963  24.0457
2   2004            Anykščių rajonas           704  55.5167  25.1000
3   2004                   Birštonas            81  54.6167  24.0167
4   2004               Biržų rajonas           615  56.2000  24.7500
5   2004                Druskininkai           315  53.9833  23.9833
6   2004                  Elektrėnai           305  54.7833  24.6667
7   2004           Ignalinos rajonas           402  55.3500  26.1667
8   2004             Jonavos rajonas          1163  55.0667  24.2833
9   2004            Joniškio rajonas           375  56.2333  23.6167

   Gyventoju_tankis  Bedarbiu_sk  Imigrantu_sk  Medianinis_amzius  Moteru  \
0             34.30       2770.0          66.0               37.0  1140.0
1            886.95       2490.5          71.0               38.5  1074.0
2             19.10       1017.0          14.0               42.0  1135.0
3             42.30        139.0           9.0               40.0  1194.0
4             23.20       1592.0          24.0               39.0  1132.0
5             54.30       2183.0          48.0               39.0  1200.0
6             55.00        426.0          26.0               38.0  1109.0
7             14.70       1501.0          30.0               43.0  1120.0
8             54.60       3282.0         159.0               35.0  1125.0
9             26.90       2240.0          31.0               37.0  1129.0

   Apyvarta  Policija  Skurdas  Pasalpa_gaunantys  gyventoju_skaicius  \
0       NaN      69.0      NaN             1557.0             28951.0
1       NaN     355.0      NaN             1071.5             50897.0
2       NaN      78.0      NaN             1115.0             33783.0
3       NaN      22.0      NaN              143.0              5240.0
4       NaN      84.0      NaN             1111.0             34266.0
5       NaN      78.0      NaN             1186.0             24665.0
6       NaN      64.0      NaN              349.0             28015.0
7       NaN      65.0      NaN              991.0             21944.0
8       NaN     125.0      NaN             2417.0             51510.0
9       NaN      83.0      NaN             1721.0             31012.0

   Vaikai_nesimokantys  Uzmokestis
0                  NaN         NaN
1                  NaN         NaN
2                  NaN         NaN
3                  NaN         NaN
4                  NaN         NaN
5                  NaN         NaN
6                  NaN         NaN
7                  NaN         NaN
8                  NaN         NaN
9                  NaN         NaN

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius,Vaikai_nesimokantys,Uzmokestis
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0,NaN,NaN
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0,NaN,NaN
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0,NaN,NaN
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0,NaN,NaN
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0,115.0,2033.3
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0,140.0,1879.9
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0,361.0,2022.0
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0,60.0,2153.4
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0,65.0,1929.5

## Alkoholio įperkamumas/vartojimas

In [33]:
alkoholis_iperkamumas = pd.read_csv('oficialios statistikos /alkoholio perkamoji galia.csv')
alkoholis_iperkamumas = alkoholis_iperkamumas[alkoholis_iperkamumas['Alkoholiniai gėrimai'].str.contains("Importinis alus skardinėse","litrai", na=False)]

In [34]:
alkoholis_iperkamumas

,Laikotarpis,Rodiklis,Alkoholiniai gėrimai,Matavimo vienetai,Reikšmė
13,2024,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,475.0
28,2023,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,437.0
43,2022,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,441.0
58,2021,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,436.0
73,2020,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,415.0
88,2019,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,370.0
103,2018,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,327.0
118,2017,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,306.0
133,2016,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,307.0
148,2015,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,301.0
163,2014,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,269.0
178,2013,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,272.0
193,2012,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,273.0
208,2011,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,316.0
223,2010,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,307.0
238,2009,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,313.0
253,2008,Vidutinio mėnesinio neto darbo užmokesčio alko...,Importinis alus skardinėse,litrai,344.0

In [35]:
def priskirti_reiksme(pagrindinis_df, saltinis_df, naujas_stulpelis, metai_stulpelis='Metai', laikotarpis_stulpelis='Laikotarpis', reiksme_stulpelis='Reikšmė'):
    for _, eilute in saltinis_df.iterrows():
        laikotarpis = eilute[laikotarpis_stulpelis]
        reiksme = eilute[reiksme_stulpelis]
        pagrindinis_df.loc[pagrindinis_df[metai_stulpelis] == laikotarpis, naujas_stulpelis] = reiksme
    return pagrindinis_df

df = priskirti_reiksme(df,alkoholis_iperkamumas, 'alkoholio_iperkamumas')
df

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius,Vaikai_nesimokantys,Uzmokestis,alkoholio_iperkamumas
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0,NaN,NaN,NaN
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0,NaN,NaN,NaN
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0,NaN,NaN,NaN
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0,NaN,NaN,NaN
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0,115.0,2033.3,NaN
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0,140.0,1879.9,NaN
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0,361.0,2022.0,NaN
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0,60.0,2153.4,NaN
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0,65.0,1929.5,NaN

In [36]:
alkoholis_suvartojimas = pd.read_csv('oficialios statistikos /alkoholio suvartojimas vienam gyventojui.csv')
alkoholis_suvartojimas

,Laikotarpis,Rodiklis,Matavimo vienetai,Reikšmė
0,2024,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",8.8
1,2023,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.3
2,2022,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.5
3,2021,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",10.3
4,2020,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.7
5,2019,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.5
6,2018,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.6
7,2017,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",10.5
8,2016,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.6
9,2015,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",12.4
10,2014,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",12.7
11,2013,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",12.9
12,2012,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",13.0
13,2011,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",12.7
14,2010,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.6
15,2009,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.1
16,2008,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.8
17,2007,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.7
18,2006,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",11.1
19,2005,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",10.4
20,2004,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",10.1
21,2003,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.3
22,2002,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",9.1
23,2001,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",8.5
24,2000,"Legalių alkoholinių gėrimų suvartojimas, tenka...","litrais, absoliutaus (100%) alkoholio",7.8

In [37]:
df = priskirti_reiksme(df,alkoholis_suvartojimas, 'alkoholio_suvartojimas')
df

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius,Vaikai_nesimokantys,Uzmokestis,alkoholio_iperkamumas,alkoholio_suvartojimas
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0,NaN,NaN,NaN,10.1
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0,NaN,NaN,NaN,10.1
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0,NaN,NaN,NaN,10.1
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0,NaN,NaN,NaN,10.1
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0,NaN,NaN,NaN,10.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0,115.0,2033.3,NaN,NaN
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0,140.0,1879.9,NaN,NaN
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0,361.0,2022.0,NaN,NaN
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0,60.0,2153.4,NaN,NaN
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0,65.0,1929.5,NaN,NaN

# Tabako suvartojimas

In [38]:
tabako_suvartojimas = pd.read_csv('oficialios statistikos /tabako suvartojimas.csv')
tabako_suvartojimas

,Laikotarpis,Rodiklis,Tabako gaminiai,Matavimo vienetai,Reikšmė
0,2024,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1009
1,2023,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1043
2,2022,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1062
3,2021,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1050
4,2020,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,957
5,2019,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,972
6,2018,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,988
7,2017,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1023
8,2016,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1094
9,2015,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1100
10,2014,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,999
11,2013,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,947
12,2012,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,907
13,2011,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,915
14,2010,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,791
15,2009,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,849
16,2008,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1259
17,2007,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1285
18,2006,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1248
19,2005,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1205
20,2004,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1154
21,2003,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1168
22,2002,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1291
23,2001,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1327
24,2000,"Legalių tabako gaminių suvartojimas, tenkantis...",Tabako gaminiai,cigaretės,1336

In [39]:
df = priskirti_reiksme(df,tabako_suvartojimas, 'tabako_suvartojimas')
df

,Metai,Savivaldybė,Nusikaltimai,lat,lon,Gyventoju_tankis,Bedarbiu_sk,Imigrantu_sk,Medianinis_amzius,Moteru,Apyvarta,Policija,Skurdas,Pasalpa_gaunantys,gyventoju_skaicius,Vaikai_nesimokantys,Uzmokestis,alkoholio_iperkamumas,alkoholio_suvartojimas,tabako_suvartojimas
0,2004,Akmenės rajonas,470,56.2456,22.7478,34.30,2770.0,66.0,37.0,1140.0,NaN,69.0,NaN,1557.0,28951.0,NaN,NaN,NaN,10.1,1154.0
1,2004,Alytaus miestas ir rajonas,1504,54.3963,24.0457,886.95,2490.5,71.0,38.5,1074.0,NaN,355.0,NaN,1071.5,50897.0,NaN,NaN,NaN,10.1,1154.0
2,2004,Anykščių rajonas,704,55.5167,25.1000,19.10,1017.0,14.0,42.0,1135.0,NaN,78.0,NaN,1115.0,33783.0,NaN,NaN,NaN,10.1,1154.0
3,2004,Birštonas,81,54.6167,24.0167,42.30,139.0,9.0,40.0,1194.0,NaN,22.0,NaN,143.0,5240.0,NaN,NaN,NaN,10.1,1154.0
4,2004,Biržų rajonas,615,56.2000,24.7500,23.20,1592.0,24.0,39.0,1132.0,NaN,84.0,NaN,1111.0,34266.0,NaN,NaN,NaN,10.1,1154.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2025,Šiaulių rajonas,434,55.8667,23.1833,22.20,2004.0,357.0,46.0,1058.0,NaN,NaN,25.7,1146.0,40120.0,115.0,2033.3,NaN,NaN,NaN
1294,2025,Šilalės rajonas,150,55.4833,22.1833,17.30,998.0,115.0,47.0,1076.0,NaN,NaN,35.3,582.0,20531.0,140.0,1879.9,NaN,NaN,NaN
1295,2025,Šilutės rajonas,478,55.3500,21.4667,22.70,2048.0,508.0,46.0,1102.0,NaN,NaN,33.2,998.0,38181.0,361.0,2022.0,NaN,NaN,NaN
1296,2025,Širvintų rajonas,143,55.0500,24.9500,16.10,800.0,130.0,47.0,1111.0,NaN,NaN,21.1,249.0,14577.0,60.0,2153.4,NaN,NaN,NaN
1297,2025,Švenčionių rajonas,204,55.1333,26.0000,12.70,1168.0,140.0,49.0,1113.0,NaN,NaN,21.4,395.0,21459.0,65.0,1929.5,NaN,NaN,NaN

In [40]:
df.to_csv("df.csv", index=False)