In [2]:
import glob
import json
import pandas as pd
import re


data = {}
for file_path in glob.glob('prir_*.json'):
    with open(file_path, 'r', encoding='utf-8') as f:
        data[file_path] = json.load(f)

In [3]:
dfs = []
for file_path in sorted(glob.glob('prir_*.json')):
    date_match = re.search(r'prir_(\d{4}_\d{2}_\d{2})', file_path)
    date = date_match.group(1).replace('_', '-') if date_match else 'unknown'

    with open(file_path, 'r', encoding='utf-8') as f:
        df = pd.json_normalize(json.load(f))  
        df['report_date'] = date
        dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)
print(combined_df.head())

         id  infoGavimoLaikas  registravimoData        ivykioData  \
0  16337964  2019-01-01 00:00  2019-01-01 00:00  2019-01-01 00:00
1  16337965  2019-01-01 00:00  2019-01-01 00:00  2019-01-01 00:00
2  16337966  2019-01-01 00:00  2019-01-01 00:00  2019-01-01 00:00
3  16337888  2018-12-31 23:59  2019-01-01 00:00  2018-12-31 23:59
4  16337967  2019-01-01 00:02  2019-01-01 00:02  2019-01-01 00:02

  ivykioDataIki kategorija pranesimoFormaKt        createDate  \
0           NaN          C            BPCIS  2019-01-01 00:00
1           NaN          C            BPCIS  2019-01-01 00:00
2           NaN          B            BPCIS  2019-01-01 00:00
3           NaN          C              NaN  2019-01-01 00:00
4           NaN          B            BPCIS  2019-01-01 00:02

     lastChangeDate teisesPazeidimoPozymis  ... arDalyvaujaNepilnameciai  \
0  2019-01-04 16:02                   Kita  ...                      NaN
1  2019-01-02 09:54                   Kita  ...                      0.0
2  2020-01-28 06:26                   Kita  ...                      1.0
3  2019-01-01 00:07                   Kita  ...                      0.0
4  2019-01-03 16:17                   Kita  ...                      NaN

             vieta     vieta2 valstybe        vietove  \
0             kita        NaN  Lietuva  Tryškių mstl.
1             kita        NaN  Lietuva    Vilkaviškis
2             kita        NaN  Lietuva       Klaipėda
3  įstaiga (įmonė)  kita (55)  Lietuva   Druskininkai
4       gatvė (02)        NaN  Lietuva   Ruklos mstl.

               savivaldybe     seniunija     gatve kertantiGatve report_date
0       Telšių rajono sav.  Tryškių sen.  Žemaitės           NaN  2019-03-31
1  Vilkaviškio rajono sav.   Vilkaviškis  Žalumynų           NaN  2019-03-31
2    Klaipėdos miesto sav.      Klaipėda  Žalgirio           NaN  2019-03-31
3         Druskininkų sav.           NaN   Vytauto           NaN  2019-03-31
4      Jonavos rajono sav.   Ruklos sen.    Ruklio           NaN  2019-03-31

[5 rows x 26 columns]

In [4]:
display(combined_df)

,id,infoGavimoLaikas,registravimoData,ivykioData,ivykioDataIki,kategorija,pranesimoFormaKt,createDate,lastChangeDate,teisesPazeidimoPozymis,...,arDalyvaujaNepilnameciai,vieta,vieta2,valstybe,vietove,savivaldybe,seniunija,gatve,kertantiGatve,report_date
0,16337964,2019-01-01 00:00,2019-01-01 00:00,2019-01-01 00:00,NaN,C,BPCIS,2019-01-01 00:00,2019-01-04 16:02,Kita,...,NaN,kita,NaN,Lietuva,Tryškių mstl.,Telšių rajono sav.,Tryškių sen.,Žemaitės,NaN,2019-03-31
1,16337965,2019-01-01 00:00,2019-01-01 00:00,2019-01-01 00:00,NaN,C,BPCIS,2019-01-01 00:00,2019-01-02 09:54,Kita,...,0.0,kita,NaN,Lietuva,Vilkaviškis,Vilkaviškio rajono sav.,Vilkaviškis,Žalumynų,NaN,2019-03-31
2,16337966,2019-01-01 00:00,2019-01-01 00:00,2019-01-01 00:00,NaN,B,BPCIS,2019-01-01 00:00,2020-01-28 06:26,Kita,...,1.0,kita,NaN,Lietuva,Klaipėda,Klaipėdos miesto sav.,Klaipėda,Žalgirio,NaN,2019-03-31
3,16337888,2018-12-31 23:59,2019-01-01 00:00,2018-12-31 23:59,NaN,C,NaN,2019-01-01 00:00,2019-01-01 00:07,Kita,...,0.0,įstaiga (įmonė),kita (55),Lietuva,Druskininkai,Druskininkų sav.,NaN,Vytauto,NaN,2019-03-31
4,16337967,2019-01-01 00:02,2019-01-01 00:02,2019-01-01 00:02,NaN,B,BPCIS,2019-01-01 00:02,2019-01-03 16:17,Kita,...,NaN,gatvė (02),NaN,Lietuva,Ruklos mstl.,Jonavos rajono sav.,Ruklos sen.,Ruklio,NaN,2019-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4605353,31387395,2024-12-31 23:56,2024-12-31 23:56,2024-12-31 23:56,NaN,A,BPCIS,2024-12-31 23:56,2025-01-07 10:28,Kita,...,0.0,kita,NaN,Lietuva,Vilnius,Vilniaus miesto sav.,NaN,Erfurto,NaN,2024-12-31
4605354,31387396,2024-12-31 23:56,2024-12-31 23:56,2024-12-31 23:56,NaN,B,BPCIS,2024-12-31 23:56,2025-01-02 07:34,Administracinis nusižengimas,...,NaN,kita,NaN,Lietuva,Pagojo k.,Kelmės rajono sav.,Kelmės apylinkių sen.,Pagojo,NaN,2024-12-31
4605355,31387328,2024-12-31 23:52,2024-12-31 23:57,2024-12-31 23:52,NaN,C,NaN,2024-12-31 23:57,2025-01-01 09:36,Kita,...,0.0,viešoji vieta (01),NaN,Lietuva,Tauragė,Tauragės rajono sav.,NaN,V. Kudirkos,NaN,2024-12-31
4605356,31387329,2024-12-31 23:57,2024-12-31 23:59,2024-12-31 23:57,NaN,C,NaN,2024-12-31 23:59,2025-01-03 10:15,Kita,...,NaN,gatvė (02),NaN,Lietuva,Šiauliai,Šiaulių miesto sav.,NaN,Vilniaus,NaN,2024-12-31
4605357,31387397,2024-12-31 23:59,2024-12-31 23:59,2024-12-31 23:59,NaN,B,BPCIS,2024-12-31 23:59,2025-01-01 00:54,Administracinis nusižengimas,...,NaN,gyvenamoji patalpa,butas (04),Lietuva,Klaipėda,Klaipėdos miesto sav.,NaN,Taikos pr.,NaN,2024-12-31

In [11]:
combined_df['registravimoData'] = pd.to_datetime(combined_df['registravimoData'], errors='coerce')

combined_df.to_csv('prir_combined_crime_data.csv', index=False, encoding='utf-8')

In [13]:
combined_df

0               Telšių rajono sav.
1          Vilkaviškio rajono sav.
2            Klaipėdos miesto sav.
3                 Druskininkų sav.
4              Jonavos rajono sav.
                    ...
4605353       Vilniaus miesto sav.
4605354         Kelmės rajono sav.
4605355       Tauragės rajono sav.
4605356        Šiaulių miesto sav.
4605357      Klaipėdos miesto sav.
Name: savivaldybe, Length: 4605358, dtype: str

In [14]:
test = pd.read_csv('prir_combined_crime_data.csv')

In [15]:
test

,id,infoGavimoLaikas,registravimoData,ivykioData,ivykioDataIki,kategorija,pranesimoFormaKt,createDate,lastChangeDate,teisesPazeidimoPozymis,...,arDalyvaujaNepilnameciai,vieta,vieta2,valstybe,vietove,savivaldybe,seniunija,gatve,kertantiGatve,report_date
0,16337964,2019-01-01 00:00,2019-01-01 00:00:00,2019-01-01 00:00,NaN,C,BPCIS,2019-01-01 00:00,2019-01-04 16:02,Kita,...,NaN,kita,NaN,Lietuva,Tryškių mstl.,Telšių rajono sav.,Tryškių sen.,Žemaitės,NaN,2019-03-31
1,16337965,2019-01-01 00:00,2019-01-01 00:00:00,2019-01-01 00:00,NaN,C,BPCIS,2019-01-01 00:00,2019-01-02 09:54,Kita,...,0.0,kita,NaN,Lietuva,Vilkaviškis,Vilkaviškio rajono sav.,Vilkaviškis,Žalumynų,NaN,2019-03-31
2,16337966,2019-01-01 00:00,2019-01-01 00:00:00,2019-01-01 00:00,NaN,B,BPCIS,2019-01-01 00:00,2020-01-28 06:26,Kita,...,1.0,kita,NaN,Lietuva,Klaipėda,Klaipėdos miesto sav.,Klaipėda,Žalgirio,NaN,2019-03-31
3,16337888,2018-12-31 23:59,2019-01-01 00:00:00,2018-12-31 23:59,NaN,C,NaN,2019-01-01 00:00,2019-01-01 00:07,Kita,...,0.0,įstaiga (įmonė),kita (55),Lietuva,Druskininkai,Druskininkų sav.,NaN,Vytauto,NaN,2019-03-31
4,16337967,2019-01-01 00:02,2019-01-01 00:02:00,2019-01-01 00:02,NaN,B,BPCIS,2019-01-01 00:02,2019-01-03 16:17,Kita,...,NaN,gatvė (02),NaN,Lietuva,Ruklos mstl.,Jonavos rajono sav.,Ruklos sen.,Ruklio,NaN,2019-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4605353,31387395,2024-12-31 23:56,2024-12-31 23:56:00,2024-12-31 23:56,NaN,A,BPCIS,2024-12-31 23:56,2025-01-07 10:28,Kita,...,0.0,kita,NaN,Lietuva,Vilnius,Vilniaus miesto sav.,NaN,Erfurto,NaN,2024-12-31
4605354,31387396,2024-12-31 23:56,2024-12-31 23:56:00,2024-12-31 23:56,NaN,B,BPCIS,2024-12-31 23:56,2025-01-02 07:34,Administracinis nusižengimas,...,NaN,kita,NaN,Lietuva,Pagojo k.,Kelmės rajono sav.,Kelmės apylinkių sen.,Pagojo,NaN,2024-12-31
4605355,31387328,2024-12-31 23:52,2024-12-31 23:57:00,2024-12-31 23:52,NaN,C,NaN,2024-12-31 23:57,2025-01-01 09:36,Kita,...,0.0,viešoji vieta (01),NaN,Lietuva,Tauragė,Tauragės rajono sav.,NaN,V. Kudirkos,NaN,2024-12-31
4605356,31387329,2024-12-31 23:57,2024-12-31 23:59:00,2024-12-31 23:57,NaN,C,NaN,2024-12-31 23:59,2025-01-03 10:15,Kita,...,NaN,gatvė (02),NaN,Lietuva,Šiauliai,Šiaulių miesto sav.,NaN,Vilniaus,NaN,2024-12-31
4605357,31387397,2024-12-31 23:59,2024-12-31 23:59:00,2024-12-31 23:59,NaN,B,BPCIS,2024-12-31 23:59,2025-01-01 00:54,Administracinis nusižengimas,...,NaN,gyvenamoji patalpa,butas (04),Lietuva,Klaipėda,Klaipėdos miesto sav.,NaN,Taikos pr.,NaN,2024-12-31